## Abdul Wassay
## PIAIC-117504
## Batch 07

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(a.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(type(a))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
np.show_config()

1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
print(a.ndim)

1


8. Create a boolean array with all the True values

In [8]:
trues = np.ones(10, dtype='bool')
print(trues)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
arr_2D = np.arange(10).reshape(2,5)
print(arr_2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


10. Create a three dimensional array



In [10]:
arr_3D = np.arange(16).reshape(4,2,2)
print(arr_3D)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vector = np.arange(10)
print(vector[::-1])

[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(float_arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
resultant = arr1 * arr2
print(resultant)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
resultant = arr1 > arr2
print(resultant)

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(10)
odd = arr[(arr%2) != 0]
print(odd)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
arr[odd] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr2d = np.ones((5,5))
arr2d[1:-1, 1:-1] = 0
print(arr2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.arange(1, 10).reshape(3,3)
arr2d[1, 1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d[0])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d = np.arange(10).reshape(2,5)
print(arr2[1, 1]) # second value of second 1D array

2.0


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.arange(10).reshape(2,5) 
print(arr2d[:2, 1:2])   # first two rows in third column

[[1]
 [6]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.random.randn(10,10)
print('Shape: ' + str(arr.shape))
print('Minimum: ' + str(arr.min()))
print('Maximum: ' + str(arr.max()))

Shape: (10, 10)
Minimum: -1.9924158728198278
Maximum: 2.444728073109737


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_idx = np.where(a==b)
print(common_idx)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names != 'Will'])

[[-0.03859769  0.61707068  1.02705436 -0.29374218]
 [-0.21240759 -0.03421342  1.33413547 -1.21847535]
 [ 2.44347994  0.97300902 -1.19076982 -0.33729195]
 [ 1.0838397  -0.37114241  0.5155871  -0.14081637]
 [-0.07084868 -1.24379787 -0.16318164  1.38449681]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

filterr = any(names != 'Will') and any(names != 'Jeo')
print(data[filterr])

[[[-0.4823914   0.08585728 -0.08217795  0.50698538]
  [ 0.52507724 -1.14490267 -0.47209968  1.0201037 ]
  [-0.25427471  0.11432076 -0.27352532 -0.02225092]
  [-0.84707921  0.87594924  0.83613641 -0.99867741]
  [ 0.47774996 -0.87874728 -0.31463738 -0.59602755]
  [-0.25032954 -0.8385808  -0.53353455  0.56918271]
  [ 0.49445829 -1.30212598  0.59412273 -0.36953288]]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr2d = np.arange(1, 16).reshape(5,3) 
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr3d = np.arange(1, 17).reshape(2,2,4) 
print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [33]:
print(np.swapaxes(arr3d, 1, 2))

[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.random.randint(0,10, 10)

print(np.where((np.sqrt(arr) < 0.5) , 0, arr))

[3 0 8 1 7 8 7 0 8 5]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)

print(np.maximum(arr1, arr2))

[-1.0809939   1.94900516  0.17249276  0.08461759 -0.31240287  0.15014876
  0.27836166  0.48473898  0.55434196  1.70568769 -0.20620195  0.09474885]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(np.sort(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print(a[~(np.isin(a, b))])

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

sampleArray[:, 1:2] = newColumn.reshape(3,1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
arr = np.random.randn(20)
print(np.cumsum(arr))

[-0.07663864  0.58836661  1.07818247  2.06827486  2.41876521  2.73138303
  0.59845065  0.75505167  0.52192084  0.59874676 -0.07508901  0.18133767
  0.5605721  -0.30805843 -1.16097381 -1.93026728 -0.7620821  -0.93050214
 -2.56974945 -1.06958155]
