## Abdul Wassay
## PIAIC-117504
## Batch 07

# Numpy_Assignment_02

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

<code>array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])</code>

In [2]:
arr1d = np.arange(10)
arr2d = arr1d.reshape(2,5)
print(f'Dims: {arr2d.ndim}\n2DArray:\n{arr2d}')

Dims: 2
2DArray:
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

<code>array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])</code>

In [3]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones((2,5), int)

stacked = np.vstack([arr1, arr2])
print(stacked)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

<code>array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])</code>

In [4]:
arr1 = np.arange(10).reshape(2,5)
arr2 = np.ones((2,5), int)

stacked = np.hstack([arr1, arr2])
print(stacked)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

<code>array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])</code>

In [5]:
arr2d = np.arange(10).reshape(2,5)

arr1d = arr2d.flatten()
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

<code>array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</code>

In [6]:
arr3d = np.arange(16).reshape(2,4,2)

arr1d = arr3d.flatten()
print(arr1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

<code>array([[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8],
        [ 9, 10, 11],
        [12, 13, 14]])</code>

In [7]:
arr1d = np.arange(15)

arr2d = arr1d.reshape(5,3)
print(arr2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr = np.arange(25).reshape(5,5)

arr_squared = np.square(arr)
print(arr_squared)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr = np.arange(30).reshape(5,6)

arr_mean = np.mean(arr)
print(arr_mean)

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
arr_std = np.std(arr)
print(arr_std)

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [11]:
arr_median = np.median(arr)
print(arr_median)

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
arr_trans = arr.T
print(arr_trans)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
arr = np.arange(16).reshape(4,4)

diagonals_sum = arr.trace()
print(diagonals_sum)

30


## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
determinant = np.linalg.det(arr)
print(determinant)

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [15]:
arr = np.arange(100)

print('5th percentile: ', np.round(np.percentile(arr,5),2))
print('95th percentile', np.round(np.percentile(arr,95),2))

5th percentile:  4.95
95th percentile 94.05


## Question:15

### How to find if a given array has any null values?

In [16]:
arr = np.arange(5)
print(np.isnan(arr).any())

False
